"""Regenerate musing_out/INDEX.md -- one table per family, newest family last.

    python index_musing_out.py

Reads meta/runs.jsonl for what each run actually traced, so the index reports
the run's own recorded corpus/target rather than re-deriving it from the name.
"""

import argparse
import json
import os
from collections import defaultdict
from datetime import datetime

import musing_layout as ml

_BLURB = {
    "phase0": "bootstrap and first instrumented traces",
    "phase1": "gold trajectories, ranked scorer",
    "phase2": "repeat/clean sweeps at N=8",
    "phase3": "anchor + perturbation variants (n2/n3)",
    "phase4": "N=12 sweep",
    "smoke": "smoke tests and hard baselines",
    "eval": "false-belief, goal-change and quality evals",
    "ab": "before/after A-B pair",
    "tuning": "parameter tuning: long-prompt, deadband, system, refset, expiry",
    "oppenheimer": "Oppenheimer corpus runs",
    "atla": "ATLA corpus runs",
    "bloomfield": "Bloomfield corpus runs",
    "odyssey": "Odyssey corpus runs",
    ml.MISC: "unclassified",
}


def human(n):
    for unit in ("B", "K", "M", "G"):
        if n < 1024 or unit == "G":
            return f"{n:.0f}{unit}" if unit == "B" else f"{n:.1f}{unit}"
        n /= 1024


def load_meta(out_dir):
    meta = {}
    path = ml.runs_jsonl(out_dir)
    if os.path.exists(path):
        for line in open(path, encoding="utf-8"):
            line = line.strip()
            if line:
                try:
                    d = json.loads(line)
                except json.JSONDecodeError:
                    continue
                meta[d.get("run_id", "")] = d  # last write wins
    return meta


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", default=ml.OUT_DIR)
    a = ap.parse_args()

    meta = load_meta(a.out_dir)
    runs_root = os.path.join(a.out_dir, ml.RUNS)

    families = defaultdict(list)
    for family in sorted(os.listdir(runs_root)) if os.path.isdir(runs_root) else []:
        fdir = os.path.join(runs_root, family)
        if not os.path.isdir(fdir):
            continue
        # A run's steps file carries the -<corpus>-<role>-<seed> suffix while its
        # log and chart do not, so group on the base id or every run is counted
        # twice. A batch log like ab.log covers several runs and stays its own
        # row -- that is what it is.
        by_run = defaultdict(list)
        fulls = defaultdict(set)
        for name in sorted(os.listdir(fdir)):
            stem = name
            for ext in (".steps.jsonl", "_weights.html", ".log", ".html", ".jsonl"):
                if stem.endswith(ext):
                    stem = stem[: -len(ext)]
                    break
            base = ml.base_run_id(stem)
            by_run[base].append(name)
            if stem != base:
                fulls[base].add(stem)
        for run, files in sorted(by_run.items()):
            size = sum(os.path.getsize(os.path.join(fdir, f)) for f in files)
            mtime = max(os.path.getmtime(os.path.join(fdir, f)) for f in files)
            ids = sorted(fulls.get(run, ()))
            d = meta.get(ids[-1], {}) if len(ids) == 1 else {}
            families[family].append({
                "run": run, "files": files, "size": size, "mtime": mtime,
                "contexts": len(ids),
                "corpus": d.get("corpus", ""), "target": d.get("target_agent", ""),
                "steps": d.get("steps", ""), "n": d.get("n_hypotheses", ""),
            })

    lines = ["# musing_out",
             "",
             f"Generated by `index_musing_out.py` on "
             f"{datetime.now().strftime('%Y-%m-%d %H:%M')}. "
             "Re-run it after a batch to refresh.",
             "",
             "```",
             "runs/<family>/   per-run artifacts: .steps.jsonl, .log, _weights.html",
             "traces/          raw tracer-*.jsonl dumps (big, machine-read)",
             "reports/         cross-run HTML",
             "meta/            runs.jsonl and the small JSON sidecars",
             "```",
             "",
             "`musing_layout.py` decides where everything goes; run_musing.py writes",
             "runs, traces and runs.jsonl straight into this tree.",
             ""]

    for family in sorted(families):
        rows = sorted(families[family], key=lambda r: r["mtime"])
        total = human(sum(r["size"] for r in rows))
        blurb = _BLURB.get(family, "")
        lines += [f"## runs/{family}",
                  "",
                  f"{len(rows)} runs, {total}" + (f" — {blurb}" if blurb else ""),
                  "",
                  "| run | corpus | target | steps | N | artifacts | size |",
                  "| --- | --- | --- | --- | --- | --- | --- |"]
        for r in rows:
            tags = " ".join(
                t for t, suf in (("steps", ".steps.jsonl"), ("log", ".log"),
                                 ("chart", "_weights.html"))
                if any(f.endswith(suf) for f in r["files"]))
            if r["contexts"] == 0:
                tags += " (batch)"
            elif r["contexts"] > 1:
                tags += f" ({r['contexts']} contexts)"
            lines.append(f"| `{r['run']}` | {r['corpus']} | {r['target']} | "
                         f"{r['steps']} | {r['n']} | {tags} | {human(r['size'])} |")
        lines.append("")

    for label, sub in (("traces", ml.TRACES), ("reports", ml.REPORTS), ("meta", ml.META)):
        d = os.path.join(a.out_dir, sub)
        if not os.path.isdir(d):
            continue
        names = sorted(n for n in os.listdir(d) if not n.startswith("."))
        size = human(sum(os.path.getsize(os.path.join(d, n)) for n in names))
        lines += [f"## {label}/", "", f"{len(names)} files, {size}", ""]
        if sub != ml.TRACES:
            lines += [f"- `{n}`" for n in names] + [""]
        else:
            lines += ["One `tracer-…_runid-<run>_nhypotheses-<n>.jsonl` per run; "
                      "find one with `ml.find(\"tracer-*runid-<run>*.jsonl\")`.", ""]

    path = os.path.join(a.out_dir, "INDEX.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {path}  ({sum(len(v) for v in families.values())} runs "
          f"across {len(families)} families)")


if __name__ == "__main__":
    raise SystemExit(main())
